/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccordionButton: typeof import('./components/ui/AccordionButton.vue')['default']
    AdminHeader: typeof import('./components/AdminHeader.vue')['default']
    AdminNavUser: typeof import('./components/AdminNavUser.vue')['default']
    AdminSidebar: typeof import('./components/AdminSidebar.vue')['default']
    AdminSidebarLink: typeof import('./components/AdminSidebarLink.vue')['default']
    AdminUserMenu: typeof import('./components/AdminUserMenu.vue')['default']
    AlertMessage: typeof import('./components/ui/AlertMessage.vue')['default']
    App: typeof import('./layouts/app.vue')['default']
    Blank: typeof import('./layouts/blank.vue')['default']
    BulkActionBar: typeof import('./components/ui/BulkActionBar.vue')['default']
    Button: typeof import('./components/ui/inputs/Button.vue')['default']
    Checkbox: typeof import('./components/ui/inputs/Checkbox.vue')['default']
    Collapse: typeof import('./components/ui/Collapse.vue')['default']
    CollapseTransition: typeof import('./components/ui/transitions/CollapseTransition.vue')['default']
    CreateAntidetectForm: typeof import('./components/antidetect/CreateAntidetectForm.vue')['default']
    DataTable: typeof import('./components/ui/DataTable.vue')['default']
    DatePicker: typeof import('./components/ui/DatePicker.vue')['default']
    DateRangePicker: typeof import('./components/ui/DateRangePicker.vue')['default']
    Default: typeof import('./layouts/default.vue')['default']
    DropFileUpload: typeof import('./components/ui/inputs/DropFileUpload.vue')['default']
    ExpandTransition: typeof import('./components/ui/transitions/ExpandTransition.vue')['default']
    FadeTransition: typeof import('./components/ui/transitions/FadeTransition.vue')['default']
    GlobalAlert: typeof import('./components/GlobalAlert.vue')['default']
    Guest: typeof import('./layouts/guest.vue')['default']
    InviteTeam: typeof import('./components/team/InviteTeam.vue')['default']
    LabeledTextInput: typeof import('./components/ui/inputs/LabeledTextInput.vue')['default']
    Modal: typeof import('./components/ui/Modal.vue')['default']
    Pagination: typeof import('./components/ui/Pagination.vue')['default']
    PasswordInput: typeof import('./components/ui/inputs/PasswordInput.vue')['default']
    RangeSlider: typeof import('./components/ui/inputs/RangeSlider.vue')['default']
    ScaleTransition: typeof import('./components/ui/transitions/ScaleTransition.vue')['default']
    ScrollBox: typeof import('./components/ui/ScrollBox.vue')['default']
    SearchInput: typeof import('./components/ui/inputs/SearchInput.vue')['default']
    SlideTransition: typeof import('./components/ui/transitions/SlideTransition.vue')['default']
    Spinner: typeof import('./components/ui/Spinner.vue')['default']
    StatsCard: typeof import('./components/ui/StatsCard.vue')['default']
    SupportAgentDialog: typeof import('./components/SupportAgentDialog.vue')['default']
    SwitchInput: typeof import('./components/ui/inputs/SwitchInput.vue')['default']
    Tab: typeof import('./components/ui/tab/Tab.vue')['default']
    Tabs: typeof import('./components/ui/tab/Tabs.vue')['default']
    TagMultiSelect: typeof import('./components/TagMultiSelect.vue')['default']
    TeamDetailWithLicense: typeof import('./components/team/TeamDetailWithLicense.vue')['default']
    Textarea: typeof import('./components/ui/inputs/Textarea.vue')['default']
    TextInput: typeof import('./components/ui/inputs/TextInput.vue')['default']
    ThemeToggle: typeof import('./components/ui/ThemeToggle.vue')['default']
    Toolbar: typeof import('./components/ui/Toolbar.vue')['default']
    UpdateAccountFacebook: typeof import('./components/facebook/UpdateAccountFacebook.vue')['default']
    UpdateFingerprint: typeof import('./components/fingerprint/UpdateFingerprint.vue')['default']
    UpdateTeam: typeof import('./components/team/UpdateTeam.vue')['default']
  }
}
