/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountCookySchema extends BaseModel {
  static $columns = ['accountId', 'createdAt', 'domain', 'expires', 'httpOnly', 'id', 'key', 'path', 'sameSite', 'secure', 'updatedAt', 'value'] as const
  $columns = AccountCookySchema.$columns
  @column()
  declare accountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare domain: string | null
  @column()
  declare expires: bigint | number | null
  @column()
  declare httpOnly: boolean | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare key: string
  @column()
  declare path: string | null
  @column()
  declare sameSite: string | null
  @column()
  declare secure: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string
}

export class CampaignAccountSchema extends BaseModel {
  static $columns = ['accountId', 'campaignId', 'createdAt', 'id', 'status', 'updatedAt'] as const
  $columns = CampaignAccountSchema.$columns
  @column()
  declare accountId: string
  @column()
  declare campaignId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CampaignGroupSchema extends BaseModel {
  static $columns = ['campaignId', 'createdAt', 'groupId', 'id', 'processedAt', 'status', 'updatedAt'] as const
  $columns = CampaignGroupSchema.$columns
  @column()
  declare campaignId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare groupId: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare processedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CampaignProfileSchema extends BaseModel {
  static $columns = ['campaignId', 'createdAt', 'id', 'profileId', 'status', 'updatedAt'] as const
  $columns = CampaignProfileSchema.$columns
  @column()
  declare campaignId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare profileId: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CampaignRuntimeStateSchema extends BaseModel {
  static $columns = ['campaignId', 'createdAt', 'currentAccountId', 'currentAction', 'currentBatch', 'currentGroupId', 'currentLabel', 'currentProfileId', 'discoveredCount', 'etaSeconds', 'failedCount', 'id', 'lastTickAt', 'meta', 'pendingCount', 'persistedCount', 'processedTargets', 'runId', 'runningCount', 'skippedCount', 'stage', 'startedAt', 'status', 'successCount', 'targetType', 'totalBatches', 'totalTargets', 'updatedAt'] as const
  $columns = CampaignRuntimeStateSchema.$columns
  @column()
  declare campaignId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currentAccountId: string | null
  @column()
  declare currentAction: string | null
  @column()
  declare currentBatch: number | null
  @column()
  declare currentGroupId: string | null
  @column()
  declare currentLabel: string | null
  @column()
  declare currentProfileId: string | null
  @column()
  declare discoveredCount: number
  @column()
  declare etaSeconds: number | null
  @column()
  declare failedCount: number
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastTickAt: DateTime | null
  @column()
  declare meta: any | null
  @column()
  declare pendingCount: number
  @column()
  declare persistedCount: number
  @column()
  declare processedTargets: number
  @column()
  declare runId: string | null
  @column()
  declare runningCount: number
  @column()
  declare skippedCount: number
  @column()
  declare stage: string | null
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare successCount: number
  @column()
  declare targetType: string | null
  @column()
  declare totalBatches: number | null
  @column()
  declare totalTargets: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CampaignSchema extends BaseModel {
  static $columns = ['advanceMode', 'config', 'createdAt', 'endedAt', 'fingerprintId', 'headless', 'id', 'maxAccounts', 'maxConcurrency', 'maxDelayMs', 'maxTargets', 'minGroupMember', 'name', 'startedAt', 'status', 'targetGroupType', 'type', 'updatedAt', 'useProxy', 'userId'] as const
  $columns = CampaignSchema.$columns
  @column()
  declare advanceMode: boolean | null
  @column()
  declare config: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare endedAt: DateTime | null
  @column()
  declare fingerprintId: string | null
  @column()
  declare headless: boolean | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare maxAccounts: number
  @column()
  declare maxConcurrency: number
  @column()
  declare maxDelayMs: number
  @column()
  declare maxTargets: number | null
  @column()
  declare minGroupMember: number | null
  @column()
  declare name: string
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare targetGroupType: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare useProxy: boolean
  @column()
  declare userId: string
}

export class DeviceActivationSchema extends BaseModel {
  static $columns = ['appVersion', 'createdAt', 'deviceId', 'deviceName', 'firstActivatedAt', 'id', 'lastIp', 'lastVerifiedAt', 'licenseId', 'os', 'osVersion', 'revokedAt', 'status', 'updatedAt', 'userId'] as const
  $columns = DeviceActivationSchema.$columns
  @column()
  declare appVersion: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceId: string
  @column()
  declare deviceName: string | null
  @column.dateTime()
  declare firstActivatedAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastIp: string | null
  @column.dateTime()
  declare lastVerifiedAt: DateTime | null
  @column()
  declare licenseId: string
  @column()
  declare os: string
  @column()
  declare osVersion: string | null
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class FacebookAccountSchema extends BaseModel {
  static $columns = ['createdAt', 'fbUserId', 'id', 'label', 'lastUsedAt', 'notes', 'profileUrl', 'sessionStatus', 'updatedAt', 'userId'] as const
  $columns = FacebookAccountSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fbUserId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare label: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare notes: string | null
  @column()
  declare profileUrl: string | null
  @column()
  declare sessionStatus: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class FacebookGroupSchema extends BaseModel {
  static $columns = ['createdAt', 'groupId', 'groupName', 'groupType', 'groupUrl', 'id', 'memberCount', 'sourceFriendUrl', 'sourceKeyword', 'sourceType', 'tags', 'updatedAt', 'userId'] as const
  $columns = FacebookGroupSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare groupId: string
  @column()
  declare groupName: string | null
  @column()
  declare groupType: string
  @column()
  declare groupUrl: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare memberCount: number | null
  @column()
  declare sourceFriendUrl: string | null
  @column()
  declare sourceKeyword: string | null
  @column()
  declare sourceType: string
  @column()
  declare tags: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class FacebookProfileSchema extends BaseModel {
  static $columns = ['createdAt', 'followerCount', 'followingCount', 'friendCount', 'id', 'lastAction', 'lastActionAt', 'lastActionMessage', 'lastActionStatus', 'lifecycleStatus', 'mutualFriendCount', 'profileId', 'profileName', 'profileUrl', 'relationshipStatus', 'sourceType', 'sourceUrl', 'tags', 'updatedAt', 'userId'] as const
  $columns = FacebookProfileSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare followerCount: number | null
  @column()
  declare followingCount: number | null
  @column()
  declare friendCount: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastAction: string | null
  @column.dateTime()
  declare lastActionAt: DateTime | null
  @column()
  declare lastActionMessage: string | null
  @column()
  declare lastActionStatus: string | null
  @column()
  declare lifecycleStatus: string
  @column()
  declare mutualFriendCount: number | null
  @column()
  declare profileId: string
  @column()
  declare profileName: string | null
  @column()
  declare profileUrl: string | null
  @column()
  declare relationshipStatus: string
  @column()
  declare sourceType: string
  @column()
  declare sourceUrl: string | null
  @column()
  declare tags: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class FingerprintProfileSchema extends BaseModel {
  static $columns = ['browserType', 'browserVersion', 'canvasNoise', 'clientHints', 'createdAt', 'deviceType', 'id', 'locale', 'name', 'osType', 'osVersion', 'rawFingerprint', 'screenHeight', 'screenWidth', 'timezone', 'updatedAt', 'userAgent', 'userId', 'webglRenderer', 'webglVendor'] as const
  $columns = FingerprintProfileSchema.$columns
  @column()
  declare browserType: string
  @column()
  declare browserVersion: string | null
  @column()
  declare canvasNoise: number | null
  @column()
  declare clientHints: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare locale: string | null
  @column()
  declare name: string
  @column()
  declare osType: string
  @column()
  declare osVersion: string | null
  @column()
  declare rawFingerprint: any | null
  @column()
  declare screenHeight: number | null
  @column()
  declare screenWidth: number | null
  @column()
  declare timezone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string
  @column()
  declare webglRenderer: string | null
  @column()
  declare webglVendor: string | null
}

export class LicenseSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'issuedAt', 'key', 'maxDevices', 'notes', 'plan', 'status', 'updatedAt', 'userId'] as const
  $columns = LicenseSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare issuedAt: DateTime
  @column()
  declare key: string
  @column()
  declare maxDevices: number
  @column()
  declare notes: string | null
  @column()
  declare plan: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class PersonalSettingSchema extends BaseModel {
  static $columns = ['createdAt', 'emailConfig', 'enableNotification', 'id', 'notificationEvents', 'slackConfig', 'telegramConfig', 'typeNotification', 'updatedAt', 'userId', 'webhookUrl'] as const
  $columns = PersonalSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare emailConfig: any | null
  @column()
  declare enableNotification: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare notificationEvents: any | null
  @column()
  declare slackConfig: any | null
  @column()
  declare telegramConfig: any | null
  @column()
  declare typeNotification: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare webhookUrl: string | null
}

export class ProxySchema extends BaseModel {
  static $columns = ['asn', 'country', 'createdAt', 'host', 'id', 'lastCheckedAt', 'password', 'port', 'protocol', 'responseMs', 'status', 'updatedAt', 'userId', 'username'] as const
  $columns = ProxySchema.$columns
  @column()
  declare asn: string | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare host: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastCheckedAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare port: number
  @column()
  declare protocol: string
  @column()
  declare responseMs: number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare username: string | null
}

export class SessionLogSchema extends BaseModel {
  static $columns = ['accountId', 'action', 'campaignId', 'createdAt', 'durationMs', 'groupId', 'id', 'message', 'screenshotPath', 'status', 'workerId'] as const
  $columns = SessionLogSchema.$columns
  @column()
  declare accountId: string | null
  @column()
  declare action: string
  @column()
  declare campaignId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationMs: number | null
  @column()
  declare groupId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare message: string | null
  @column()
  declare screenshotPath: string | null
  @column()
  declare status: string
  @column()
  declare workerId: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isActive', 'lastLoginAt', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean | null
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
